#
# @lc app=leetcode id=3677 lang=python3
#
# [3677] Count Binary Palindromic Numbers
#

# @lc code=start
class Solution:
    def countBinaryPalindromes(self, n: int) -> int:
        if n == 0:
            return 1
        
        s = bin(n)[2:]
        L = len(s)
        count = 1  # Including 0 as a binary palindrome
        
        # 1. Count all binary palindromes with bit-length less than the bit-length of n
        for length in range(1, L):
            # For length l, bits are fixed by the first ceil(l/2) positions.
            # First bit must be 1, so (ceil(l/2) - 1) bits are free.
            k = (length + 1) // 2
            count += 1 << (k - 1)
            
        # 2. Count binary palindromes with the same bit-length as n
        k = (L + 1) // 2
        prefix_str = s[:k]
        prefix_val = int(prefix_str, 2)
        
        # Smallest possible prefix for length L is 1 followed by (k-1) zeros
        min_prefix = 1 << (k - 1)
        
        # Number of valid palindromes with prefixes strictly less than n's prefix
        count += (prefix_val - min_prefix)
        
        # 3. Check if the palindrome generated by n's own prefix is <= n
        first_half = prefix_str
        if L % 2 == 0:
            # Even length: mirror the entire prefix
            full_pal_str = first_half + first_half[::-1]
        else:
            # Odd length: mirror the prefix excluding the middle bit
            full_pal_str = first_half + first_half[:-1][::-1]
            
        if int(full_pal_str, 2) <= n:
            count += 1
            
        return count
# @lc code=end